# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1dc00429522cf33f6d8055a1b4558627cbce73f2698bd354ab505cfad21c148f8a4b27644b94e40bc2b17778cc5afb5e1b98f6f60d6a356b95113d6c4d560a8

test:
  secret_key_base: 80a81841a8090fc4d08e3849f60f484bb115740dafe209922e09ecebf9830e0d93f94266d8d32921c789414e7861e44a6f159391179b76382c396d22617efab2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
